[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = ["pip3 install anthropic requests python-dotenv"]

[start]
cmd = "python3 main.py"
